### PR TITLE
Add `OlmMachine.registerUserIdentityCallback`

### PR DESCRIPTION
**Pull request by richvdh**
Expose the new stream added in ~~https://github.com/matrix-org/matrix-rust-sdk/pull/2516~~ https://github.com/matrix-org/matrix-rust-sdk/pull/2373

Part of https://github.com/vector-im/crypto-internal/issues/148

### CODE REVIEW

**Review by Hywan — APPROVED** [review]
Quick review, it looks good :-).

**Comment by richvdh** [comment]
Thanks. We're replacing https://github.com/matrix-org/matrix-rust-sdk/pull/2516 with https://github.com/matrix-org/matrix-rust-sdk/pull/2373, so this needs some tweaks

**Comment by richvdh** [comment]
going to assume that the minor tweaks here aren't significant enough to need re-review.

**Comment by Hywan** [comment]
Yup, sure.

**Pull request merged**
